# Generated by Django 3.2.9 on 2021-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20211125_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='real_cost_currency',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(),
        ),
    ]
